### YamlMime:UniversalReference
ms.openlocfilehash: 6cb0f3f80bc511a0865f3a5609cf1784ff077b9b
ms.sourcegitcommit: 87f95d58ec8de16e115bc344efeb084afc346b74
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 08/12/2018
ms.locfileid: "40058240"
items:
- uid: azure-event-hubs.ErrorNameConditionMapper
  name: ErrorNameConditionMapper
  fullName: ErrorNameConditionMapper
  children:
  - azure-event-hubs.ErrorNameConditionMapper.ArgumentError
  - azure-event-hubs.ErrorNameConditionMapper.UnauthorizedError
  - azure-event-hubs.ErrorNameConditionMapper.ConnectionForcedError
  - azure-event-hubs.ErrorNameConditionMapper.ConnectionRedirectError
  - azure-event-hubs.ErrorNameConditionMapper.DecodeError
  - azure-event-hubs.ErrorNameConditionMapper.DetachForcedError
  - azure-event-hubs.ErrorNameConditionMapper.ErrantLinkError
  - azure-event-hubs.ErrorNameConditionMapper.FrameSizeTooSmallError
  - azure-event-hubs.ErrorNameConditionMapper.FramingError
  - azure-event-hubs.ErrorNameConditionMapper.HanldeInUseError
  - azure-event-hubs.ErrorNameConditionMapper.IllegalStateError
  - azure-event-hubs.ErrorNameConditionMapper.InternalServerError
  - azure-event-hubs.ErrorNameConditionMapper.InvalidFieldError
  - azure-event-hubs.ErrorNameConditionMapper.InvalidOperationError
  - azure-event-hubs.ErrorNameConditionMapper.LinkRedirectError
  - azure-event-hubs.ErrorNameConditionMapper.MessageLockLostError
  - azure-event-hubs.ErrorNameConditionMapper.MessageTooLargeError
  - azure-event-hubs.ErrorNameConditionMapper.ArgumentOutOfRangeError
  - azure-event-hubs.ErrorNameConditionMapper.NotImplementedError
  - azure-event-hubs.ErrorNameConditionMapper.OperationCancelledError
  - azure-event-hubs.ErrorNameConditionMapper.PreconditionFailedError
  - azure-event-hubs.ErrorNameConditionMapper.QuotaExceededError
  - azure-event-hubs.ErrorNameConditionMapper.ReceiverDisconnectedError
  - azure-event-hubs.ErrorNameConditionMapper.ResourceDeletedError
  - azure-event-hubs.ErrorNameConditionMapper.ResourceLockedError
  - azure-event-hubs.ErrorNameConditionMapper.SenderBusyError
  - azure-event-hubs.ErrorNameConditionMapper.ServerBusyError
  - azure-event-hubs.ErrorNameConditionMapper.ServiceCommunicationError
  - azure-event-hubs.ErrorNameConditionMapper.ServiceUnavailableError
  - azure-event-hubs.ErrorNameConditionMapper.SessionCannotBeLockedError
  - azure-event-hubs.ErrorNameConditionMapper.SessionLockLostError
  - azure-event-hubs.ErrorNameConditionMapper.SessionWindowViolationError
  - azure-event-hubs.ErrorNameConditionMapper.TransferLimitExceededError
  - azure-event-hubs.ErrorNameConditionMapper.UnattachedHandleError
  - azure-event-hubs.ErrorNameConditionMapper.MessagingEntityDisabledError
  langs:
  - typeScript
  type: enum
  summary: <span data-ttu-id="af968-101">Ordnet die Bedingungen mit den Namen des Fehlers an.</span><span class="sxs-lookup"><span data-stu-id="af968-101">Maps the conditions to the Error names.</span></span>
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ArgumentError
  name: ArgumentError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-102">Fehler wird ausgelöst, wenn ein ungültiges Argument empfangen wurde.</span><span class="sxs-lookup"><span data-stu-id="af968-102">Error is thrown when an incorrect argument was received.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.UnauthorizedError
  name: UnauthorizedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-103">Fehler wird ausgelöst, wenn die Parameter falsch sind und der Server Verbindung verweigert.</span><span class="sxs-lookup"><span data-stu-id="af968-103">Error is thrown when the connection parameters are wrong and the server refused the connection.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ConnectionForcedError
  name: ConnectionForcedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-104">Fehler wird ausgelöst, wenn ein Operator blockiert wird, um die Verbindung aus irgendeinem Grund zu beenden.</span><span class="sxs-lookup"><span data-stu-id="af968-104">Error is thrown when an operator intervened to close the connection for some reason.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ConnectionRedirectError
  name: ConnectionRedirectError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-105">Fehler wird ausgelöst, wenn der Container nicht mehr auf die aktuelle Verbindung verfügbar ist.</span><span class="sxs-lookup"><span data-stu-id="af968-105">Error is thrown when the container is no longer available on the current connection.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.DecodeError
  name: DecodeError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-106">Fehler wird ausgelöst, wenn Daten nicht decodiert werden können.</span><span class="sxs-lookup"><span data-stu-id="af968-106">Error is thrown when data could not be decoded.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.DetachForcedError
  name: DetachForcedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-107">Fehler wird ausgelöst, wenn ein Operator dazwischen aus irgendeinem Grund getrennt kamen.</span><span class="sxs-lookup"><span data-stu-id="af968-107">Error is thrown when an operator intervened to detach for some reason.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ErrantLinkError
  name: ErrantLinkError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-108">Fehler wird ausgelöst, als Eingabe für einen Link empfangen wurde, die mit einem Fehler getrennt wurde.</span><span class="sxs-lookup"><span data-stu-id="af968-108">Error is thrown when input was received for a link that was detached with an error.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.FrameSizeTooSmallError
  name: FrameSizeTooSmallError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-109">Fehler wird ausgelöst, wenn der Peer ein Frames senden kann, da die kleinste Codierung der performative mit aktuell gültigen Werten zu groß für innerhalb eines Rahmens, der die vereinbarten maximale Rahmengröße wäre.</span><span class="sxs-lookup"><span data-stu-id="af968-109">Error is thrown when the peer cannot send a frame because the smallest encoding of the performative with the currently valid values would be too large to fit within a frame of the agreed maximum frame size.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.FramingError
  name: FramingError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-110">Fehler wird ausgelöst, wenn Sie ein gültigen Frame-Header aus den eingehenden Datenstrom gebildet werden kann nicht.</span><span class="sxs-lookup"><span data-stu-id="af968-110">Error is thrown when a valid frame header cannot be formed from the incoming byte stream.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.HanldeInUseError
  name: HanldeInUseError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-111">Fehler wird ausgelöst, wenn anfügen empfangen wurde, verwenden ein Handle, das bereits für eine angefügte Link verwendet wird.</span><span class="sxs-lookup"><span data-stu-id="af968-111">Error is thrown when an attach was received using a handle that is already in use for an attached link.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.IllegalStateError
  name: IllegalStateError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-112">Fehler wird ausgelöst, wenn es sich bei der Peer ein Frames gesendet, das in den aktuellen Zustand nicht zulässig ist.</span><span class="sxs-lookup"><span data-stu-id="af968-112">Error is thrown when the peer sent a frame that is not permitted in the current state.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.InternalServerError
  name: InternalServerError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-113">Fehler wird ausgelöst, wenn ein interner Serverfehler ist aufgetreten.</span><span class="sxs-lookup"><span data-stu-id="af968-113">Error is thrown when an internal server error occured.</span></span> <span data-ttu-id="af968-114">Sie können einen Fehler erkannt werden können?</span><span class="sxs-lookup"><span data-stu-id="af968-114">You may have found a bug?</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.InvalidFieldError
  name: InvalidFieldError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-115">Fehler wird ausgelöst, wenn ein ungültiges Feld in einem Frame-Text übergeben wurde und der Vorgang nicht fortgesetzt werden konnte.</span><span class="sxs-lookup"><span data-stu-id="af968-115">Error is thrown when an invalid field was passed in a frame body, and the operation could not proceed.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.InvalidOperationError
  name: InvalidOperationError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-116">Fehler wird ausgelöst, wenn ein Vorgang versucht wird, jedoch ist nicht zulässig.</span><span class="sxs-lookup"><span data-stu-id="af968-116">Error is thrown when an operation is attempted but is not allowed.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.LinkRedirectError
  name: LinkRedirectError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-117">Fehler wird ausgelöst, wenn die angegebene Adresse nicht in einer sich auf dem aktuellen Container aufgelöst werden.</span><span class="sxs-lookup"><span data-stu-id="af968-117">Error is thrown when the address provided cannot be resolved to a terminus at the current container.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.MessageLockLostError
  name: MessageLockLostError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-118">Fehler wird ausgelöst, wenn die Sperre für die Nachricht verloren geht.</span><span class="sxs-lookup"><span data-stu-id="af968-118">Error is thrown when the lock on the message is lost.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.MessageTooLargeError
  name: MessageTooLargeError
  children: []
  langs:
  - typeScript
  summary: '<span data-ttu-id="af968-119">Fehler wird ausgelöst, wenn die gesendete Nachricht zu groß: die maximale Größe beträgt 256Kb.</span><span class="sxs-lookup"><span data-stu-id="af968-119">Error is thrown when the message sent is too large: the maximum size is 256Kb.</span></span>'
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ArgumentOutOfRangeError
  name: ArgumentOutOfRangeError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-120">Fehler wird ausgelöst, wenn ein Argument einen Wert aufweist, der außerhalb des zulässigen Bereichs.</span><span class="sxs-lookup"><span data-stu-id="af968-120">Error is thrown when an argument has a value that is out of the admissible range.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.NotImplementedError
  name: NotImplementedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-121">Fehler wird ausgelöst, wenn eine Funktion ist noch nicht implementiert, aber der Platzhalter vorhanden ist.</span><span class="sxs-lookup"><span data-stu-id="af968-121">Error is thrown when a feature is not implemented yet but the placeholder is present.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.OperationCancelledError
  name: OperationCancelledError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-122">Fehler wird ausgelöst, wenn der Server die Operation aufgrund eines internen Fehlers abgebrochen wird.</span><span class="sxs-lookup"><span data-stu-id="af968-122">Error is thrown when server cancels the operation due to an internal issue.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.PreconditionFailedError
  name: PreconditionFailedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-123">Fehler wird ausgelöst, wenn eine Bedingung, die zum Ausführen eines Vorgangs erfüllt wurden sollte kein war.</span><span class="sxs-lookup"><span data-stu-id="af968-123">Error is thrown when a condition that should have been met in order to execute an operation was not.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.QuotaExceededError
  name: QuotaExceededError
  children: []
  langs:
  - typeScript
  summary: >-
    <span data-ttu-id="af968-124">Fehler wird ausgelöst, die die Azure Event Hub/Service Bus-Kontingent wurde überschritten.</span><span class="sxs-lookup"><span data-stu-id="af968-124">Error is thrown the the Azure EventHub/ServiceBus quota has been exceeded.</span></span>

    <span data-ttu-id="af968-125">Kontingente werden in regelmäßigen Abständen zurückgesetzt, diesen Vorgang müssen Sie warten, bis dahin.</span><span class="sxs-lookup"><span data-stu-id="af968-125">Quotas are reset periodically, this operation will have to wait until then.</span></span>

    <span data-ttu-id="af968-126">Die Messagingentität hat die maximal zulässige Größe erreicht.</span><span class="sxs-lookup"><span data-stu-id="af968-126">The messaging entity has reached its maximum allowable size.</span></span>

    <span data-ttu-id="af968-127">Dies kann passieren, wenn bereits die maximale Anzahl von fünf Empfängern für eine bestimmte Consumergruppe geöffnet wurde.</span><span class="sxs-lookup"><span data-stu-id="af968-127">This can happen if the maximum number of receivers (which is 5) has already been opened on a per-consumer group level.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ReceiverDisconnectedError
  name: ReceiverDisconnectedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-128">Fehler wird ausgelöst, wenn mindestens zwei Instanzen mit der gleichen Partition mit den Werten der verschiedenen Epoche verbinden.</span><span class="sxs-lookup"><span data-stu-id="af968-128">Error is thrown when two or more instances connect to the same partition with different epoch values.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ResourceDeletedError
  name: ResourceDeletedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-129">Fehler wird ausgelöst, wenn eine Entität, mit denen der Client arbeiten wird gelöscht wurde.</span><span class="sxs-lookup"><span data-stu-id="af968-129">Error is thrown when a server entity the client is working with has been deleted.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ResourceLockedError
  name: ResourceLockedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-130">Fehler wird ausgelöst, wenn der Client hat versucht, mit einer Server-Entität funktioniert auf die er keinen Zugriff hat, da ein anderer Client damit arbeitet.</span><span class="sxs-lookup"><span data-stu-id="af968-130">Error is thrown when the client attempted to work with a server entity to which it has no access because another client is working with it.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.SenderBusyError
  name: SenderBusyError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-131">Fehler wird ausgelöst, wenn der Client-Absender nicht ausreichend verknüpfungsguthaben zum Senden der Nachricht verfügt.</span><span class="sxs-lookup"><span data-stu-id="af968-131">Error is thrown when the client sender does not have enough link credits to send the message.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ServerBusyError
  name: ServerBusyError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-132">Fehler wird ausgelöst, wenn der Server ausgelastet ist.</span><span class="sxs-lookup"><span data-stu-id="af968-132">Error is thrown when the server is busy.</span></span> <span data-ttu-id="af968-133">Aufrufer sollten einen Moment warten, und wiederholen Sie den Vorgang.</span><span class="sxs-lookup"><span data-stu-id="af968-133">Callers should wait a while and retry the operation.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ServiceCommunicationError
  name: ServiceCommunicationError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-134">Fehler für die Signalisierung allgemeiner Kommunikationsfehler im Zusammenhang mit der Messagingvorgänge ausgeführt wird.</span><span class="sxs-lookup"><span data-stu-id="af968-134">Error for signaling general communication errors related to messaging operations.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.ServiceUnavailableError
  name: ServiceUnavailableError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-135">Fehler wird ausgelöst, wenn der Dienst nicht verfügbar ist.</span><span class="sxs-lookup"><span data-stu-id="af968-135">Error is thrown when the service is unavailable.</span></span> <span data-ttu-id="af968-136">Der Vorgang muss wiederholt werden.</span><span class="sxs-lookup"><span data-stu-id="af968-136">The operation should be retried.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.SessionCannotBeLockedError
  name: SessionCannotBeLockedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-137">Fehler wird ausgelöst, wenn die Azure Service Bus-Sitzung nicht gesperrt werden kann.</span><span class="sxs-lookup"><span data-stu-id="af968-137">Error is thrown when the Azure ServiceBus session cannot be locked.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.SessionLockLostError
  name: SessionLockLostError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-138">Fehler wird ausgelöst, wenn die Sperre für die Azure Service Bus-Sitzung verloren geht.</span><span class="sxs-lookup"><span data-stu-id="af968-138">Error is thrown when the lock on the Azure ServiceBus session is lost.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.SessionWindowViolationError
  name: SessionWindowViolationError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-139">Fehler wird ausgelöst, wenn der Peers eingehende Fenster für die Sitzung verletzt.</span><span class="sxs-lookup"><span data-stu-id="af968-139">Error is thrown when the peer violated incoming window for the session.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.TransferLimitExceededError
  name: TransferLimitExceededError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-140">Fehler wird ausgelöst, wenn es sich bei der Peer Weitere darauf folgenden Nachrichtenübermittlungen als die derzeit auf den Link zulässige gesendet.</span><span class="sxs-lookup"><span data-stu-id="af968-140">Error is thrown when the peer sent more message transfers than currently allowed on the link.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.UnattachedHandleError
  name: UnattachedHandleError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-141">Fehler wird ausgelöst, wenn ein Frame (andere als anfügen) empfangen wurde verweisen auf ein Handle für die derzeit nicht in Gebrauch eines angefügten links ist.</span><span class="sxs-lookup"><span data-stu-id="af968-141">Error is thrown when a frame (other than attach) was received referencing a handle which is not currently in use of an attached link.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ErrorNameConditionMapper.MessagingEntityDisabledError
  name: MessagingEntityDisabledError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="af968-142">Fehler wird ausgelöst, wenn Access/mit einer deaktivierten messagingentität eine Verbindung herstellen möchten.</span><span class="sxs-lookup"><span data-stu-id="af968-142">Error is thrown when trying to access/connect to a disabled messaging entity.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
